openapi: 3.0.3
info:
  title: View Self Assessment Account
  version: 0.3.0
servers:
- url: https://test-api.service.hmrc.gov.uk
  description: Sandbox
- url: https://api.service.hmrc.gov.uk
  description: Production
paths:
  /individuals/self-assessment/breakdown/{utr}:
    get:
      tags:
      - Self Assessment Account Details
      summary: Account Details
      description: |
        <b>Examples</b><br>
        /individuals/self-assessment/breakdown/1234567890?fromDate=2024-08-04
      parameters:
      - name: Authorization
        in: header
        description: |
          An OAuth 2.0 Bearer Token with the *read:self-assessment* scope.
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: Bearer bb7fed3fe10dd235a2ccda3d50fb
      - name: fromDate
        in: query
        description: |
          "The start date for the tax data retrieval period (YYYY-MM-DD format)"
        required: false
        style: form
        explode: true
        schema:
          pattern: "^(((19|20)([2468][048]|[13579][26]|0[48])|2000)[-]02[-]29|((19|20)[0-9]{2}[-](0[469]|11)[-](0[1-9]|1[0-9]|2[0-9]|30)|(19|20)[0-9]{2}[-](0[13578]|1[02])[-](0[1-9]|[12][0-9]|3[01])|(19|20)[0-9]{2}[-]02[-](0[1-9]|1[0-9]|2[0-8])))$"
          type: string
        example: 2023-01-01
      - name: utr
        in: path
        description: Unique Tax Payer Reference
        required: true
        style: simple
        explode: false
        schema:
          pattern: "^\\d{10}$"
          type: string
          example:
          - "1234567890"
      responses:
        "200":
          description: Successful
          content:
            application/json;charset=UTF-8:
              schema:
                required:
                - balanceDetails
                type: object
                properties:
                  balanceDetails:
                    required:
                    - totalBalance
                    - totalCreditAvailable
                    - totalOverdueBalance
                    - totalPayableBalance
                    - totalPendingBalance
                    type: object
                    properties:
                      totalOverdueBalance:
                        maximum: 99999999999.99
                        minimum: 0
                        type: number
                        description: Total of all charges with a due date in the past.
                      totalPayableBalance:
                        maximum: 99999999999.99
                        minimum: 0
                        type: number
                        description: Total of all charges due within the next 30 days.
                      earliestPayableDueDate:
                        pattern: "^(((19|20)([2468][048]|[13579][26]|0[48])|2000)[-]02[-]29|((19|20)[0-9]{2}[-](0[469]|11)[-](0[1-9]|1[0-9]|2[0-9]|30)|(19|20)[0-9]{2}[-](0[13578]|1[02])[-](0[1-9]|[12][0-9]|3[01])|(19|20)[0-9]{2}[-]02[-](0[1-9]|1[0-9]|2[0-8])))$"
                        type: string
                        description: The earliest due date for charges due within
                          the next 30 days.
                      totalPendingBalance:
                        maximum: 99999999999.99
                        minimum: 0
                        type: number
                        description: Total of all charges due in 30 days or more.
                      earliestPendingDueDate:
                        pattern: "^(((19|20)([2468][048]|[13579][26]|0[48])|2000)[-]02[-]29|((19|20)[0-9]{2}[-](0[469]|11)[-](0[1-9]|1[0-9]|2[0-9]|30)|(19|20)[0-9]{2}[-](0[13578]|1[02])[-](0[1-9]|[12][0-9]|3[01])|(19|20)[0-9]{2}[-]02[-](0[1-9]|1[0-9]|2[0-8])))$"
                        type: string
                        description: The earliest due date for charges due in 30 days
                          or more.
                      totalBalance:
                        maximum: 99999999999.99
                        minimum: 0
                        type: number
                        description: "Combined total of overdue, payable, and pending\
                          \ charges."
                      totalCreditAvailable:
                        maximum: 99999999999.99
                        minimum: 0
                        type: number
                        description: Total credit currently accrued on the account.
                      codedOutDetail:
                        type: array
                        description: Coded out liabilities
                  chargeDetails:
                    type: array
                  refundDetails:
                    type: array
                  paymentHistoryDetails:
                    type: array
                additionalProperties: false
                description: Provides a summary of the taxpayer's current position
              examples:
                example 1:
                  value:
                    balanceDetails:
                      totalOverdueBalance: 500
                      totalPayableBalance: 500
                      earliestPayableDueDate: 2025-04-30
                      totalPendingBalance: 1500
                      earliestPendingDueDate: 2025-07-15
                      totalBalance: 2000
                      totalCreditAvailable: 0
                      codedOutDetail:
                      - totalAmount: 200
                        effectiveStartDate: 2023-04-06
                        effectiveEndDate: 2024-04-01
                    chargeDetails:
                    - chargeId: AB1234567
                      creationDate: 2025-01-15
                      chargeType: ITSA
                      chargeAmount: 1250
                      outstandingAmount: 500
                      taxYear: 2024-2025
                      dueDate: 2025-04-30
                      amendments:
                      - amendmentDate: 2025-04-15
                        amendmentAmount: 500
                        amendmentReason: Payment
                        isPaymentRelated: true
                        paymentMethod: bank_transfer
                        paymentDate: 2025-04-10
                    - chargeId: EF2345678
                      creationDate: 2024-02-10
                      chargeType: NICS
                      chargeAmount: 2200
                      outstandingAmount: 0
                      taxYear: 2023-2024
                      dueDate: 2024-04-01
                      outstandingInterestDue: 20
                      accruingInterestPeriod:
                        interestStartDate: 2024-05-01
                        interestEndDate: 2024-12-01
                      accruingInterestRate: 0.05
                      amendments:
                      - amendmentDate: 2024-12-08
                        amendmentAmount: 2058.33
                        amendmentReason: Payment
                        isPaymentRelated: true
                        paymentMethod: bank_transfer
                        paymentDate: 2024-12-03
                    - chargeId: KL3456789
                      creationDate: 2025-05-22
                      chargeType: VATC
                      chargeAmount: 1500
                      outstandingAmount: 1500
                      taxYear: 2025-2026
                      dueDate: 2025-07-15
                    refundDetails:
                    - refundDate: 2024-01-10
                      refundMethod: bank_transfer
                      refundRequestDate: 2023-12-12
                      refundRequestAmount: 350
                      refundDescription: From overpayment from return 05 APR 23
                      interestAddedToRefund: 5.25
                      totalRefundAmount: 355.25
                      refundStatus: processed
                    paymentHistoryDetails:
                    - paymentAmount: 500
                      paymentReference: PAY123456
                      paymentMethod: bank_transfer
                      paymentDate: 2025-04-11
                      processedDate: 2025-04-15
                      allocationReference: AB1234567
                    - paymentAmount: 2058.33
                      paymentReference: PAY112233
                      paymentMethod: bank_transfer
                      paymentDate: 2024-12-04
                      processedDate: 2024-12-08
                      allocationReference: EF2345678
                    - paymentAmount: 200
                      paymentReference: PAY888233
                      paymentMethod: bank_transfer
                      paymentDate: 2023-12-04
                      processedDate: 2023-12-08
                      allocationReference: EF2345678
        "400":
          description: Bad request
          content:
            application/json;charset=UTF-8:
              schema:
                required:
                - message
                type: object
                properties:
                  message:
                    type: string
                    description: Error message.
                additionalProperties: false
              examples:
                error400ResponseBodyExample:
                  value:
                    message: Invalid request format or parameters.
        "401":
          description: Unauthorised
          content:
            application/json;charset=UTF-8:
              schema:
                required:
                - message
                type: object
                properties:
                  message:
                    type: string
                    description: Error message.
                additionalProperties: false
              examples:
                error401ResponseBodyExample:
                  value:
                    message: Authorisation failed.
        "403":
          description: Forbidden
          content:
            application/json;charset=UTF-8:
              schema:
                required:
                - message
                type: object
                properties:
                  message:
                    type: string
                    description: Error message.
                additionalProperties: false
              examples:
                error403ResponseBodyExample:
                  value:
                    message: Access not permitted.
        "404":
          description: Not found
          content:
            application/json;charset=UTF-8:
              schema:
                required:
                - message
                type: object
                properties:
                  message:
                    type: string
                    description: Error message.
                additionalProperties: false
              examples:
                error404ResponseBodyExample:
                  value:
                    message: No data found for the UTR provided.
        "500":
          description: Internal Server Error
          content:
            application/json;charset=UTF-8:
              schema:
                required:
                - message
                type: object
                properties:
                  message:
                    type: string
                    description: Error message.
                additionalProperties: false
              examples:
                error500ResponseBodyExample:
                  value:
                    message: Unexpected internal error. Please contact service desk.
        "503":
          description: Service unavailable
          content:
            application/json;charset=UTF-8:
              schema:
                required:
                - message
                type: object
                properties:
                  message:
                    type: string
                    description: Error message.
                additionalProperties: false
              examples:
                error503ResponseBodyExample:
                  value:
                    message: Service unavailable. Please try again later.
      security:
      - userRestricted:
        - read:self-assessment
components:
  schemas:
    amountType_11_2:
      multipleOf: 0.01
      maximum: 99999999999.99
      minimum: -99999999999.99
      type: number
      description: Currency amount. 13-digits total with 2 decimal places
    positiveAmountType:
      multipleOf: 0.01
      maximum: 99999999999.99
      minimum: 0
      type: number
      description: All numeric fields. 13-digits total with 2 decimal places and positive
    dateType:
      pattern: "^(((19|20)([2468][048]|[13579][26]|0[48])|2000)[-]02[-]29|((19|20)[0-9]{2}[-](0[469]|11)[-](0[1-9]|1[0-9]|2[0-9]|30)|(19|20)[0-9]{2}[-](0[13578]|1[02])[-](0[1-9]|[12][0-9]|3[01])|(19|20)[0-9]{2}[-]02[-](0[1-9]|1[0-9]|2[0-8])))$"
      type: string
    responseType:
      required:
      - message
      type: object
      properties:
        message:
          type: string
          description: Error message.
      additionalProperties: false
    successResponse:
      required:
      - balanceDetails
      type: object
      properties:
        balanceDetails:
          required:
          - totalBalance
          - totalCreditAvailable
          - totalOverdueBalance
          - totalPayableBalance
          - totalPendingBalance
          type: object
          properties:
            totalOverdueBalance:
              maximum: 99999999999.99
              minimum: 0
              type: number
              description: Total of all charges with a due date in the past.
            totalPayableBalance:
              maximum: 99999999999.99
              minimum: 0
              type: number
              description: Total of all charges due within the next 30 days.
            earliestPayableDueDate:
              pattern: "^(((19|20)([2468][048]|[13579][26]|0[48])|2000)[-]02[-]29|((19|20)[0-9]{2}[-](0[469]|11)[-](0[1-9]|1[0-9]|2[0-9]|30)|(19|20)[0-9]{2}[-](0[13578]|1[02])[-](0[1-9]|[12][0-9]|3[01])|(19|20)[0-9]{2}[-]02[-](0[1-9]|1[0-9]|2[0-8])))$"
              type: string
              description: The earliest due date for charges due within the next 30
                days.
            totalPendingBalance:
              maximum: 99999999999.99
              minimum: 0
              type: number
              description: Total of all charges due in 30 days or more.
            earliestPendingDueDate:
              pattern: "^(((19|20)([2468][048]|[13579][26]|0[48])|2000)[-]02[-]29|((19|20)[0-9]{2}[-](0[469]|11)[-](0[1-9]|1[0-9]|2[0-9]|30)|(19|20)[0-9]{2}[-](0[13578]|1[02])[-](0[1-9]|[12][0-9]|3[01])|(19|20)[0-9]{2}[-]02[-](0[1-9]|1[0-9]|2[0-8])))$"
              type: string
              description: The earliest due date for charges due in 30 days or more.
            totalBalance:
              maximum: 99999999999.99
              minimum: 0
              type: number
              description: "Combined total of overdue, payable, and pending charges."
            totalCreditAvailable:
              maximum: 99999999999.99
              minimum: 0
              type: number
              description: Total credit currently accrued on the account.
            codedOutDetail:
              type: array
              description: Coded out liabilities
        chargeDetails:
          type: array
        refundDetails:
          type: array
        paymentHistoryDetails:
          type: array
      additionalProperties: false
      description: Provides a summary of the taxpayer's current position
    yearType:
      allOf:
      - pattern: "^([0-9]{4})$"
        type: string
    taxYearType:
      pattern: "^([0-9]{4})-([0-9]{4})$"
      type: string
  parameters:
    fromDate:
      name: fromDate
      in: query
      required: false
      style: form
      explode: true
      schema:
        $ref: '#/components/schemas/dateType'
      example: 2023-01-01
    utr:
      name: utr
      in: path
      description: Unique Tax Payer Reference
      required: true
      style: simple
      explode: false
      schema:
        pattern: "^\\d{10}$"
        type: string
        example:
        - "1234567890"
  examples:
    error400ResponseBodyExample:
      value:
        message: Invalid request format or parameters.
    error401ResponseBodyExample:
      value:
        message: Authorisation failed.
    error403ResponseBodyExample:
      value:
        message: Access not permitted.
    error404ResponseBodyExample:
      value:
        message: No data found for the UTR provided.
    error500ResponseBodyExample:
      value:
        message: Unexpected internal error. Please contact service desk.
    error503ResponseBodyExample:
      value:
        message: Service unavailable. Please try again later.
    successResponseExample:
      value:
        balanceDetails:
          totalOverdueBalance: 500
          totalPayableBalance: 500
          earliestPayableDueDate: 2025-04-30
          totalPendingBalance: 1500
          earliestPendingDueDate: 2025-07-15
          totalBalance: 2000
          totalCreditAvailable: 0
          codedOutDetail:
          - totalAmount: 200
            effectiveStartDate: 2023-04-06
            effectiveEndDate: 2024-04-01
        chargeDetails:
        - chargeId: AB1234567
          creationDate: 2025-01-15
          chargeType: ITSA
          chargeAmount: 1250
          outstandingAmount: 500
          taxYear: 2024-2025
          dueDate: 2025-04-30
          amendments:
          - amendmentDate: 2025-04-15
            amendmentAmount: 500
            amendmentReason: Payment
            isPaymentRelated: true
            paymentMethod: bank_transfer
            paymentDate: 2025-04-10
        - chargeId: EF2345678
          creationDate: 2024-02-10
          chargeType: NICS
          chargeAmount: 2200
          outstandingAmount: 0
          taxYear: 2023-2024
          dueDate: 2024-04-01
          outstandingInterestDue: 20
          accruingInterestPeriod:
            interestStartDate: 2024-05-01
            interestEndDate: 2024-12-01
          accruingInterestRate: 0.05
          amendments:
          - amendmentDate: 2024-12-08
            amendmentAmount: 2058.33
            amendmentReason: Payment
            isPaymentRelated: true
            paymentMethod: bank_transfer
            paymentDate: 2024-12-03
        - chargeId: KL3456789
          creationDate: 2025-05-22
          chargeType: VATC
          chargeAmount: 1500
          outstandingAmount: 1500
          taxYear: 2025-2026
          dueDate: 2025-07-15
        refundDetails:
        - refundDate: 2024-01-10
          refundMethod: bank_transfer
          refundRequestDate: 2023-12-12
          refundRequestAmount: 350
          refundDescription: From overpayment from return 05 APR 23
          interestAddedToRefund: 5.25
          totalRefundAmount: 355.25
          refundStatus: processed
        paymentHistoryDetails:
        - paymentAmount: 500
          paymentReference: PAY123456
          paymentMethod: bank_transfer
          paymentDate: 2025-04-11
          processedDate: 2025-04-15
          allocationReference: AB1234567
        - paymentAmount: 2058.33
          paymentReference: PAY112233
          paymentMethod: bank_transfer
          paymentDate: 2024-12-04
          processedDate: 2024-12-08
          allocationReference: EF2345678
        - paymentAmount: 200
          paymentReference: PAY888233
          paymentMethod: bank_transfer
          paymentDate: 2023-12-04
          processedDate: 2023-12-08
          allocationReference: EF2345678
  headers:
    Authorization:
      description: An OAuth 2.0 Bearer Token with the *read:self-assessment* scope.
      style: simple
      explode: false
      schema:
        type: string
        example: Bearer bb7fed3fe10dd235a2ccda3d50fb
  securitySchemes:
    userRestricted:
      type: oauth2
      description: "HMRC supports OAuth 2.0 for authenticating user restricted API\
        \ requests using an OAuth 2.0 Bearer Token in the AUTHORIZATION header. Please\
        \ see the [developer hub](https://developer.service.hmrc.gov.uk/api-documentation/docs/authorisation/user-restricted-endpoints)\
        \ for more details."
      flows:
        authorizationCode:
          authorizationUrl: https://api.service.hmrc.gov.uk/oauth/authorize
          tokenUrl: https://api.service.hmrc.gov.uk/oauth/token
          refreshUrl: https://api.service.hmrc.gov.uk/oauth/refresh
          scopes:
            read:self-assessment: Read self-assessment data
